from typing import Iterable, Sequence, List, Optional, overload

class Matrix4:
    """
    4x4 行列（内部は 4x4 のリストまたは長さ16のフラットリストを扱う想定）
    """
    m: List[float]
    def __init__(self, arr: Optional[Sequence[float]] = None) -> None: ...
    def set_identity(self) -> None: ...

    @overload
    def __mul__(self, other: "Matrix4") -> "Matrix4": ...
    @overload
    def __mul__(self, other: Sequence[float]) -> List[float]: ...
    def __mul__(self, other): ...

    @overload
    def __rmul__(self, other: Sequence[float]) -> List[float]: ...
    @overload
    def __rmul__(self, other: "Matrix4") -> "Matrix4": ...
    def __rmul__(self, other): ...

    def mul_vec4(self, seq: Iterable[float]) -> List[float]: ...
    def T(self) -> "Matrix4": ...
    def transposed(self) -> "Matrix4": ...
    def __repr__(self) -> str: ...
    def to_array(self) -> List[float]: ...
    def __eq__ (self, other: object) -> bool : ...

    def get_item (self,line_index:int,column_index:int) -> float :...
    def tobytes (self) -> bytes :...

    @overload
    def __getitem__(self, index: int) -> List[float]: ...
    @overload
    def __getitem__(self, index: tuple[int, int]) -> float: ...

    def set_item (self,line_index:int,column_index:int,value:float) -> None :...

    @overload
    def __setitem__(self, index: int, value: Sequence[float]) -> None: ...
    @overload
    def __setitem__(self, index: tuple[int, int], value: float) -> None: ...

    @staticmethod
    def identity() -> "Matrix4": ...
    @staticmethod
    def get_identity() -> "Matrix4" :...
    @staticmethod
    def from_list(arr: Sequence[float]) -> "Matrix4": ...
    @staticmethod
    def get_translation (x:float,y:float,z:float) -> Matrix4:...
    @staticmethod
    def create_perspective(fov_degrees:float, aspect_ratio:float, near:float, far:float)-> Matrix4:...
    @staticmethod
    def create_scale(x:float,y:float,z:float) -> Matrix4 :...
    @staticmethod
    def create_euler_angles (x:float,y:float,z:float) -> Matrix4 :...