from typing import Union, Iterator, List
import PyGame3d.vector.vec_type as vector

Number = Union[int, float]

# signature : github copilot
class Vector3:
    x: float
    y: float
    z: float

    def __init__(self, x: float, y: float, z: float) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[float]: ...

    def set(self, vec: vector.VectorLike) -> None: ...

    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def normalized(self) -> "Vector3": ...

    def dot(self, other: vector.VectorLike) -> float: ...
    def cross(self, other: vector.VectorLike) -> "Vector3": ...

    def to_list(self) -> List[float]: ...

    def __add__(self, other: Union[vector.Number, vector.VectorLike]) -> "Vector3": ...
    def __radd__(self, other: Union[vector.Number, vector.VectorLike]) -> "Vector3": ...
    def __sub__(self, other: Union[vector.Number, vector.VectorLike]) -> "Vector3": ...
    def __rsub__(self, other: Union[vector.Number, vector.VectorLike]) -> "Vector3": ...
    def __mul__(self, other: Union[vector.Number, vector.VectorLike]) -> "Vector3": ...
    def __rmul__(self, other: Union[vector.Number, vector.VectorLike]) -> "Vector3": ...
    def __truediv__(self, other: Union[vector.Number, vector.VectorLike]) -> "Vector3": ...
    def __rtruediv__(self, other: Union[vector.Number, vector.VectorLike]) -> "Vector3": ...
    def __neg__(self) -> "Vector3": ...

    def __eq__(self, other: object) -> bool: ...
